{% set name = "pygsp2" %}
{% set version = "2.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygsp2-{{ version }}.tar.gz
  sha256: 88259daa69ac8d8de7909f677289c77bcc1e833a89101bacd445e754f06d4e1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - pandas
    - networkx
    - geopy
    - matplotlib-base
    - unidecode
    - utm
    - pyxlsb

test:
  imports:
    - pygsp2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gsp-eeg/pygsp2
  summary: Graph Signal Processing in Python
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - lcortesg
