# .github/workflows/auto-merge.yml
name: Auto-Merge Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR events

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check for auto-merge conditions
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            if (pullRequest.mergeable_state === 'clean' &&
                pullRequest.state === 'open' &&
                pullRequest.merged === false &&
                pullRequest.draft === false) {
              return true;
            }

            return false;
        id: check-merge-conditions

      - name: Auto Merge Pull Request
        if: steps.check-merge-conditions.outputs.result == 'true'
        uses: pascalgn/automerge-action@v0.15.0
        with:
          merge_method: merge  # or 'merge', 'rebase' based on your preference
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
